2018-07-29 12:12:41,165 INFO: Microblog startup [in C:\Users\TBW\Documents\footy_site\app\__init__.py:49]
2018-07-29 12:12:59,010 INFO: Microblog startup [in C:\Users\TBW\Documents\footy_site\app\__init__.py:49]
2018-07-29 12:13:20,290 INFO: Microblog startup [in C:\Users\TBW\Documents\footy_site\app\__init__.py:49]
2018-07-29 12:13:56,511 INFO: Microblog startup [in C:\Users\TBW\Documents\footy_site\app\__init__.py:49]
2018-07-29 12:14:49,069 INFO: Microblog startup [in C:\Users\TBW\Documents\footy_site\app\__init__.py:49]
2018-07-29 12:23:45,559 INFO: Microblog startup [in C:\Users\TBW\Documents\footy_site\app\__init__.py:49]
2018-07-29 12:28:33,183 INFO: Microblog startup [in C:\Users\TBW\Documents\footy_site\app\__init__.py:49]
2018-07-29 12:28:40,204 INFO: Microblog startup [in C:\Users\TBW\Documents\footy_site\app\__init__.py:49]
2018-07-29 12:29:15,379 INFO: Microblog startup [in C:\Users\TBW\Documents\footy_site\app\__init__.py:49]
2018-07-29 12:29:34,773 INFO: Microblog startup [in C:\Users\TBW\Documents\footy_site\app\__init__.py:49]
2018-07-29 12:29:43,467 INFO: Microblog startup [in C:\Users\TBW\Documents\footy_site\app\__init__.py:49]
2018-07-29 12:29:50,682 INFO: Microblog startup [in C:\Users\TBW\Documents\footy_site\app\__init__.py:49]
2018-07-29 12:29:58,665 INFO: Microblog startup [in C:\Users\TBW\Documents\footy_site\app\__init__.py:49]
2018-07-29 12:30:25,916 INFO: Microblog startup [in C:\Users\TBW\Documents\footy_site\app\__init__.py:49]
2018-07-29 12:30:34,610 INFO: Microblog startup [in C:\Users\TBW\Documents\footy_site\app\__init__.py:49]
2018-07-29 12:34:33,367 INFO: Microblog startup [in C:\Users\TBW\Documents\footy_site\app\__init__.py:49]
2018-07-29 12:35:58,480 INFO: Microblog startup [in C:\Users\TBW\Documents\footy_site\app\__init__.py:49]
2018-07-29 12:39:31,065 INFO: Microblog startup [in C:\Users\TBW\Documents\footy_site\app\__init__.py:49]
2018-07-29 12:43:11,089 INFO: Microblog startup [in C:\Users\TBW\Documents\footy_site\app\__init__.py:49]
2018-07-29 12:45:29,382 INFO: Microblog startup [in C:\Users\TBW\Documents\footy_site\app\__init__.py:49]
2018-07-29 12:46:03,637 INFO: Microblog startup [in C:\Users\TBW\Documents\footy_site\app\__init__.py:49]
2018-07-29 12:48:24,492 INFO: Microblog startup [in C:\Users\TBW\Documents\footy_site\app\__init__.py:49]
2018-07-29 13:03:00,914 INFO: Microblog startup [in C:\Users\TBW\Documents\footy_site\app\__init__.py:49]
2018-07-29 13:04:08,943 INFO: Microblog startup [in C:\Users\TBW\Documents\footy_site\app\__init__.py:49]
2018-07-29 13:04:13,939 ERROR: Exception on /index [GET] [in C:\Users\TBW\Anaconda3\envs\footy\lib\site-packages\flask\app.py:1761]
Traceback (most recent call last):
  File "C:\Users\TBW\Anaconda3\envs\footy\lib\site-packages\flask\app.py", line 2292, in wsgi_app
    response = self.full_dispatch_request()
  File "C:\Users\TBW\Anaconda3\envs\footy\lib\site-packages\flask\app.py", line 1815, in full_dispatch_request
    rv = self.handle_user_exception(e)
  File "C:\Users\TBW\Anaconda3\envs\footy\lib\site-packages\flask\app.py", line 1718, in handle_user_exception
    reraise(exc_type, exc_value, tb)
  File "C:\Users\TBW\Anaconda3\envs\footy\lib\site-packages\flask\_compat.py", line 35, in reraise
    raise value
  File "C:\Users\TBW\Anaconda3\envs\footy\lib\site-packages\flask\app.py", line 1813, in full_dispatch_request
    rv = self.dispatch_request()
  File "C:\Users\TBW\Anaconda3\envs\footy\lib\site-packages\flask\app.py", line 1799, in dispatch_request
    return self.view_functions[rule.endpoint](**req.view_args)
  File "C:\Users\TBW\Anaconda3\envs\footy\lib\site-packages\flask_login\utils.py", line 261, in decorated_view
    return func(*args, **kwargs)
  File "C:\Users\TBW\Documents\footy_site\app\routes.py", line 37, in index
    prev_url=prev_url)
  File "C:\Users\TBW\Anaconda3\envs\footy\lib\site-packages\flask\templating.py", line 135, in render_template
    context, ctx.app)
  File "C:\Users\TBW\Anaconda3\envs\footy\lib\site-packages\flask\templating.py", line 117, in _render
    rv = template.render(context)
  File "C:\Users\TBW\Anaconda3\envs\footy\lib\site-packages\jinja2\asyncsupport.py", line 76, in render
    return original_render(self, *args, **kwargs)
  File "C:\Users\TBW\Anaconda3\envs\footy\lib\site-packages\jinja2\environment.py", line 1008, in render
    return self.environment.handle_exception(exc_info, True)
  File "C:\Users\TBW\Anaconda3\envs\footy\lib\site-packages\jinja2\environment.py", line 780, in handle_exception
    reraise(exc_type, exc_value, tb)
  File "C:\Users\TBW\Anaconda3\envs\footy\lib\site-packages\jinja2\_compat.py", line 37, in reraise
    raise value.with_traceback(tb)
  File "C:\Users\TBW\Documents\footy_site\app\templates\index.html", line 1, in top-level template code
    {% extends "base.html" %}
  File "C:\Users\TBW\Documents\footy_site\app\templates\base.html", line 12, in top-level template code
    <a href="{{ url_for('explore') }}">Explore</a>
  File "C:\Users\TBW\Anaconda3\envs\footy\lib\site-packages\flask\helpers.py", line 356, in url_for
    return appctx.app.handle_url_build_error(error, endpoint, values)
  File "C:\Users\TBW\Anaconda3\envs\footy\lib\site-packages\flask\app.py", line 2061, in handle_url_build_error
    reraise(exc_type, exc_value, tb)
  File "C:\Users\TBW\Anaconda3\envs\footy\lib\site-packages\flask\_compat.py", line 35, in reraise
    raise value
  File "C:\Users\TBW\Anaconda3\envs\footy\lib\site-packages\flask\helpers.py", line 345, in url_for
    force_external=external)
  File "C:\Users\TBW\Anaconda3\envs\footy\lib\site-packages\werkzeug\routing.py", line 1776, in build
    raise BuildError(endpoint, values, method, self)
werkzeug.routing.BuildError: Could not build url for endpoint 'explore'. Did you mean 'edit_profile' instead?
2018-07-29 13:06:16,770 INFO: Microblog startup [in C:\Users\TBW\Documents\footy_site\app\__init__.py:49]
2018-07-29 13:18:22,233 INFO: Microblog startup [in C:\Users\TBW\Documents\footy_site\app\__init__.py:51]
2018-07-29 13:33:50,808 INFO: Microblog startup [in C:\Users\TBW\Documents\footy_site\app\__init__.py:51]
2018-07-29 13:36:43,273 INFO: Microblog startup [in C:\Users\TBW\Documents\footy_site\app\__init__.py:51]
2018-07-29 13:37:42,459 ERROR: Exception on /reset_password_request [POST] [in C:\Users\TBW\Anaconda3\envs\footy\lib\site-packages\flask\app.py:1761]
Traceback (most recent call last):
  File "C:\Users\TBW\Anaconda3\envs\footy\lib\site-packages\flask\app.py", line 2292, in wsgi_app
    response = self.full_dispatch_request()
  File "C:\Users\TBW\Anaconda3\envs\footy\lib\site-packages\flask\app.py", line 1815, in full_dispatch_request
    rv = self.handle_user_exception(e)
  File "C:\Users\TBW\Anaconda3\envs\footy\lib\site-packages\flask\app.py", line 1718, in handle_user_exception
    reraise(exc_type, exc_value, tb)
  File "C:\Users\TBW\Anaconda3\envs\footy\lib\site-packages\flask\_compat.py", line 35, in reraise
    raise value
  File "C:\Users\TBW\Anaconda3\envs\footy\lib\site-packages\flask\app.py", line 1813, in full_dispatch_request
    rv = self.dispatch_request()
  File "C:\Users\TBW\Anaconda3\envs\footy\lib\site-packages\flask\app.py", line 1799, in dispatch_request
    return self.view_functions[rule.endpoint](**req.view_args)
  File "C:\Users\TBW\Documents\footy_site\app\routes.py", line 163, in reset_password_request
    send_password_reset_email(user)
  File "C:\Users\TBW\Documents\footy_site\app\email.py", line 26, in send_password_reset_email
    user=user, token=token))
  File "C:\Users\TBW\Anaconda3\envs\footy\lib\site-packages\flask\templating.py", line 134, in render_template
    return _render(ctx.app.jinja_env.get_or_select_template(template_name_or_list),
  File "C:\Users\TBW\Anaconda3\envs\footy\lib\site-packages\jinja2\environment.py", line 869, in get_or_select_template
    return self.get_template(template_name_or_list, parent, globals)
  File "C:\Users\TBW\Anaconda3\envs\footy\lib\site-packages\jinja2\environment.py", line 830, in get_template
    return self._load_template(name, self.make_globals(globals))
  File "C:\Users\TBW\Anaconda3\envs\footy\lib\site-packages\jinja2\environment.py", line 804, in _load_template
    template = self.loader.load(self, name, globals)
  File "C:\Users\TBW\Anaconda3\envs\footy\lib\site-packages\jinja2\loaders.py", line 113, in load
    source, filename, uptodate = self.get_source(environment, name)
  File "C:\Users\TBW\Anaconda3\envs\footy\lib\site-packages\flask\templating.py", line 58, in get_source
    return self._get_source_fast(environment, template)
  File "C:\Users\TBW\Anaconda3\envs\footy\lib\site-packages\flask\templating.py", line 86, in _get_source_fast
    raise TemplateNotFound(template)
jinja2.exceptions.TemplateNotFound: email/reset_password.html
